### ISSUE TITLE
Hello Integrity

### ISSUE THREAD

**Issue by thaiwash** [NealRame/dune2-online#1]
D:\project\dune2-online>npm run build
    
    > dune2@0.1.0 build D:\project\dune2-online
    > vue-cli-service build
    
    
    -  Building for production...
    
     ERROR  Failed to compile with 1 error                                                                          03:20:29
    
     error  in ./src/components/Screen.vue
    
    Module Error (from ./node_modules/eslint-loader/index.js):
    
    D:\project\dune2-online\src\components\Screen.vue
      18:8  error  'Scene' is defined but never used  no-unused-vars
    
    ✖ 1 problem (1 error, 0 warnings)
    
    
     @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/@vue/cli-service/node_modules/vue-loader-v16/dist??ref--0-1!./src/App.vue?vue&type=script&lang=js 5:0-45 11:12-18
     @ ./src/App.vue?vue&type=script&lang=js
     @ ./src/App.vue
     @ ./src/main.js
     @ multi ./src/main.js
    
     ERROR  Build failed with errors.
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! dune2@0.1.0 build: `vue-cli-service build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the dune2@0.1.0 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2021-03-15T01_20_30_398Z-debug.log
    
    D:\project\dune2-online>npm run build
    
    > dune2@0.1.0 build D:\project\dune2-online
    > vue-cli-service build
    
    
    -  Building for production...
    
     ERROR  Failed to compile with 1 error                                                                          03:31:46
    
    This relative module was not found:
    
    * ../core/dune2-rc in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/eslint-loader??ref--13-0!./src/worker/file.worker.js
     ERROR  Build failed with errors.
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! dune2@0.1.0 build: `vue-cli-service build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the dune2@0.1.0 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2021-03-15T01_31_46_229Z-debug.log
    
  

I tried building it, i tried removing the error line from Scene.vue but the second problem got me to stop.

**Comment by thaiwash** [comment]
Btw, will pay you 360€ over 30 years (1€ a month) if you follow my JS programming standards. [Please join my programming clan] 
laidbacksoftware@gmail.com

**Comment by NealRame** [comment]
Hello,

This project is still in its early stages. It is very, very far from being achieved. In addition, it requires generated data (Dune 2 game data) which cannot be added to the repository for intellectual property reasons.

A program (you can find it in my repos), extracts data from a zipped file then generate a _Protocol Buffer_ file containing tiles, sprites and sounds plus some javascript code to deserialise all of it. Since you have not generated those data and code you get that error.

If this project interests you, stay tuned! I work on it regularly (at my own pace) and I hope to continue until an online playable version of dune2.
